name: Trigger-GitHub-Pages-Rebuild

on:
  workflow_dispatch:

jobs:
  Trigger-GitHub-Pages-Rebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger GitHub Pages rebuild
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer $USER_TOKEN" \
        https://api.github.com/repos/${{ github.repository }}/pages/builds
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
