name: publish issues

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo -e '# User stories\n' >> issues.md
          
      - name: List v1 issues
        uses: lee-dohm/select-matching-issues@v1.2.0
        with:
          format: list
          query: label:v1 label:\"user story\"
          token: ${{ secrets.USER_TOKEN }}
          path: issues-tmp.md
          
      - run: |
          cat issues-tmp.md >> issues.md
          echo -e '\n' >> issues.md
        
      - name: List v2 issues
        uses: lee-dohm/select-matching-issues@v1.2.0
        with:
          format: list
          query: label:v2 label:\"user story\"
          token: ${{ secrets.USER_TOKEN }}
          path: issues-tmp.md

      - run: |
          cat issues-tmp.md >> issues.md
          echo -e '\n' >> issued.md

      - run: |
          sed -i 's/)/){:target="_blank" rel="noopener"}/' issues.md
          cat issues.md
          mv issues.md ./docs/user-stories-prod.md
          if [ -n "$(git status ./docs/user-stories-prod.md --porcelain)" ]; then
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add ./docs/user-stories-prod.md
            git commit -m "commit generated user stories in productie artifacts"
            git push
          fi
          

