name: publish issues

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List v1 issues
        uses: lee-dohm/select-matching-issues@v1.2.0
        with:
          format: list
          query:  'label:v1'
          token: ${{ secrets.USER_TOKEN }}
          path: issues-1.md 
      - name: List v2 issues
        uses: lee-dohm/select-matching-issues@v1.2.0
        with:
          format: list
          query:  'label:v2'
          token: ${{ secrets.USER_TOKEN }}
          path: issues-2.md
      - run: 'cat issues-1.md issues-2.md > issues.md'
      - run: 'cat issues.md'

